Feature/footer
YuliiaLukomska/project-besttim1 pull request #10
Opened 2023-10-12 16:44 UTC by Kryvoboka

2023-10-13 13:06 UTC, Mariia-Ann requested changes
Залишила всі коментарі в слаку

2023-10-14 14:29 UTC, YuliiaLukomska approved these changes

2023-10-14 14:56 UTC, YuliiaLukomska reviewed
внести правки, які обговорили в Слак

2023-10-14 17:25 UTC, YuliiaLukomska approved these changes

2023-10-14 17:27 UTC, Mariia-Ann approved these changes

2023-10-14 17:27 UTC, merged