add our-mentors css, span in html and media
YuliiaLukomska/project-besttim1 pull request #12
Opened 2023-10-12 20:40 UTC by yuliia-petrenko

2023-10-13 19:56 UTC, Mariia-Ann requested changes
коментарі залишила в слак

2023-10-15 08:57 UTC, YuliiaLukomska reviewed
інші розміри заголовку та параграфу - обговорили в Слак

2023-10-15 13:49 UTC, YuliiaLukomska reviewed
ширина лішки

2023-10-15 14:14 UTC, YuliiaLukomska approved these changes

2023-10-15 14:15 UTC, Mariia-Ann approved these changes

2023-10-15 14:16 UTC, merged